### ISSUE TITLE
Error: Too many open files

### ISSUE THREAD

**Issue by lgommans** [tvdstaaij/telegram-history-dump#101]
Traceback (most recent call last):
	11: from telegram-history-dump.rb:370:in `<main>'
	10: from telegram-history-dump.rb:370:in `each_with_index'
	 9: from telegram-history-dump.rb:370:in `each'
	 8: from telegram-history-dump.rb:373:in `block in <main>'
	 7: from telegram-history-dump.rb:181:in `dump_dialog'
	 6: from /some/path/telegram-history-dump/lib/json_lines_dumper.rb:31:in `dump_chunk'
	 5: from /some/path/telegram-history-dump/lib/json_lines_dumper.rb:31:in `new'
	 4: from /usr/lib/ruby/2.5.0/tempfile.rb:131:in `initialize'
	 3: from /usr/lib/ruby/2.5.0/tmpdir.rb:128:in `create'
	 2: from /usr/lib/ruby/2.5.0/tempfile.rb:133:in `block in initialize'
	 1: from /usr/lib/ruby/2.5.0/tempfile.rb:133:in `open'
    /usr/lib/ruby/2.5.0/tempfile.rb:133:in `initialize': Too many open files @ rb_sysopen - /tmp/telegram-history-dump[chunk1016]20180420-16570-lqp448 (Errno::EMFILE)

I assume closing file handles will resolve this, but I don't have the time to test this properly (particularly because backing up takes a while and I don't want to keep downloading my chats over and over, idk how impulsive tg is about banning these days...). For the moment, it should work to run this before running the backup:

    $ ulimit -Sn 4096

**Comment by Arunm0111986** [comment]
Pull request
