### ISSUE TITLE
> Assertion failed: (0), function tglf_fetch_message_media_new, file tgl/structures.c, line 944.

### ISSUE THREAD

**Issue by travka** [tvdstaaij/telegram-history-dump#110]
```➜  telegram-history-dump git:(master) ✗ ruby telegram-history-dump.rb
I, [2018-08-10T15:43:58.205295 #10165]  INFO -- : Attaching to telegram-cli control socket at localhost:9009
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `initialize': no implicit
 conversion of nil into String (TypeError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `new'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/json/common.rb:156:in `parse'
        from telegram-history-dump.rb:48:in `exec_tg_command'
        from telegram-history-dump.rb:334:in `<main>'
```

```> Assertion failed: (0), function tglf_fetch_message_media_new, file tgl/structures.c, line 944.
SIGNAL received
S0   telegram                            0x000000010f3c0e22 print_backtrace + 46
1   telegram                            0x000000010f3c0ebd termination_signal_handler + 109
2   libsystem_platform.dylib            0x00007fff7db77f5a _sigtramp + 26
3   ???                                 0x000000012bde87f0 0x0 + 5030971376
4   libsystem_c.dylib                   0x00007fff7d9151ae abort + 127
5   libsystem_c.dylib                   0x00007fff7d8dd1ac basename_r + 0
6   telegram                            0x000000010f3e62da tglf_fetch_message_media_new + 1218
7   telegram                            0x000000010f3ecb8b replay_log_event + 7480
8   telegram                            0x000000010f3ed5c4 add_log_event + 165
9   telegram                            0x000000010f3ee05d bl_do_create_message_new + 584
10  telegram                            0x000000010f3e6bd2 tglf_fetch_message_new + 265
11  telegram                            0x000000010f3e79e5 tglf_fetch_alloc_message_new + 151
12  telegram                            0x000000010f3e030f get_dialogs_on_answer + 456
13  telegram                            0x000000010f3d65ff tglq_query_result + 613
14  telegram                            0x000000010f3d2782 rpc_execute + 1728
15  telegram                            0x000000010f3f1f6f conn_try_read + 689
16  libevent-2.1.6.dylib                0x000000011c6c49c2 event_process_active_single_queue + 1057
17  libevent-2.1.6.dylib                0x000000011c6c1cb3 event_base_loop + 1074
18  telegram                            0x000000010f3c1457 net_loop + 162
19  telegram                            0x000000010f3c3244 accept_incoming + 0
20  telegram                            0x000000010f3c1250 main + 687
21  libdyld.dylib                       0x00007fff7d869015 start + 1
➜  ~```
how to fix that ?

**Comment by reorx** [comment]
Same problem here.

**Comment by tengshe95** [comment]
same problem

**Comment by preygithub** [comment]
Please remove the "state file" in .telegram-cli each time when you get this message.
Thanks :)
