### ISSUE TITLE
Conversion error (string into nil) in json/common.rb

### ISSUE THREAD

**Issue by larsfroelich** [tvdstaaij/telegram-history-dump#113]
I'm getting the following error after some time when backing up a large dialog:

```
Traceback (most recent call last):
        16: from telegram-history-dump.rb:375:in '<main>'
        15: from telegram-history-dump.rb:375:in 'each_with_index'
        14: from telegram-history-dump.rb:375:in 'each'
        13: from telegram-history-dump.rb:379:in 'block in <main>'
        12: from telegram-history-dump.rb:78:in 'dump_dialog'
        11: from telegram-history-dump.rb:78:in 'loop'
        10: from telegram-history-dump.rb:91:in 'block in dump_dialog'
         9: from /usr/lib/ruby/2.5.0/timeout.rb:108:in 'timeout'
         8: from /usr/lib/ruby/2.5.0/timeout.rb:33:in 'catch'
         7: from /usr/lib/ruby/2.5.0/timeout.rb:33:in 'catch'
         6: from /usr/lib/ruby/2.5.0/timeout.rb:33:in 'block in catch'
         5: from /usr/lib/ruby/2.5.0/timeout.rb:93:in 'block in timeout'
         4: from telegram-history-dump.rb:92:in 'block (2 levels) in dump_dialog'
         3: from telegram-history-dump.rb:48:in 'exec_tg_command'
         2: from /usr/lib/ruby/2.5.0/json/common.rb:156:in 'parse'
         1: from /usr/lib/ruby/2.5.0/json/common.rb:156:in 'new'
/usr/lib/ruby/2.5.0/json/common.rb:156:in 'initialize': no implicit conversion of nil into String (TypeError)
```
Had no time to look into it yet .. has anyone got an idea as to what could be causing this?

**Comment by Arunm0111986** [comment]
Need help
