### ISSUE TITLE
What part generates this error while downloading attachment? Only one chat has it.

### ISSUE THREAD

**Issue by Jimmm** [tvdstaaij/telegram-history-dump#70]
cli output:
> SIGNAL received
hbin/telegram-cli(print_backtrace+0x20)[0x4791d0]
bin/telegram-cli(termination_signal_handler+0x64)[0x479254]
/lib64/libc.so.6(+0x35140)[0x7f3315500140]
bin/telegram-cli(tgl_do_load_photo+0x14)[0x4a9ee4]
bin/telegram-cli(interpreter_ex+0x7f1)[0x482bc1]
bin/telegram-cli[0x4797b5]
/usr/lib64/libevent-2.0.so.5(+0x1c33a)[0x7f33172ba33a]
/usr/lib64/libevent-2.0.so.5(event_base_loop+0x754)[0x7f33172afad4]
bin/telegram-cli(net_loop+0xa6)[0x47a736]
bin/telegram-cli(loop+0x187)[0x47ba17]
bin/telegram-cli(main+0x2d6)[0x477a66]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f33154ecb25]
bin/telegram-cli[0x477b62]

thd output:
I, [2017-02-05T14:20:14.027687 #6254]  INFO -- : Dumping "XXX" (range 17001-17100)
E, [2017-02-05T14:20:14.357646 #6254] ERROR -- : Failed to download media file: no implicit conversion of nil into String
I, [2017-02-05T14:20:15.359382 #6254]  INFO -- : Dumping "XXX" (range 17101-17200)
telegram-history-dump.rb:35:in `write': Broken pipe (Errno::EPIPE)
        from telegram-history-dump.rb:35:in `puts'
        from telegram-history-dump.rb:35:in `exec_tg_command'
        from telegram-history-dump.rb:68:in `block in dump_dialog'
        from /usr/lib64/ruby/2.1.0/timeout.rb:91:in `block in timeout'
        from /usr/lib64/ruby/2.1.0/timeout.rb:35:in `block in catch'
        from /usr/lib64/ruby/2.1.0/timeout.rb:35:in `catch'
        from /usr/lib64/ruby/2.1.0/timeout.rb:35:in `catch'
        from /usr/lib64/ruby/2.1.0/timeout.rb:106:in `timeout'
        from telegram-history-dump.rb:67:in `dump_dialog'
        from telegram-history-dump.rb:323:in `block in <main>'
        from telegram-history-dump.rb:319:in `each'
        from telegram-history-dump.rb:319:in `each_with_index'
        from telegram-history-dump.rb:319:in `<main>'

**Comment by tvdstaaij** [comment]
Hard to tell, telegram-cli has a bunch of bugs that can cause crashes like this, especially when media files are involved. The only advice I can offer is to search telegram-cli issues and see if someone has a workaround. Otherwise you'll have to create a separate configuration file for that chat to disable media downloads or set a backlog limit.
