### ISSUE TITLE
Too many non-array chunk retries crashes the script

### ISSUE THREAD

**Issue by jmendeth** [tvdstaaij/telegram-history-dump#71]
~~~
I, [2017-02-06T01:17:07.527202 #9376]  INFO -- : Dumping "SSH&CMD_>_/dev/null#1" (range 58701-58800)
E, [2017-02-06T01:17:07.527707 #9376] ERROR -- : Telegram-cli returned a non array chunk, retrying... (1/3)
E, [2017-02-06T01:17:11.346820 #9376] ERROR -- : Telegram-cli returned a non array chunk, retrying... (2/3)
E, [2017-02-06T01:17:14.260200 #9376] ERROR -- : Telegram-cli returned a non array chunk, retrying... (3/3)
E, [2017-02-06T01:17:20.152157 #9376] ERROR -- : Telegram-cli returned a non array chunk, retrying... (4/3)
telegram-history-dump.rb:102:in `dump_dialog': Expected array (RuntimeError)
	from telegram-history-dump.rb:370:in `block in <main>'
	from telegram-history-dump.rb:366:in `each'
	from telegram-history-dump.rb:366:in `each_with_index'
	from telegram-history-dump.rb:366:in `<main>'
~~~

The retry loop is finishing (conditional being false) without printing the "Chunk will not be dumped" and setting it to `[]`. I'll open a pull request later to fix it.

**Comment by jmendeth** [comment]
Oh sorry, I just discovered this is due to #61 and has been pointed out there. Closing.
