### ISSUE TITLE
Crash while dumping (range 101-200) of a channel

### ISSUE THREAD

**Issue by ameygat** [tvdstaaij/telegram-history-dump#80]
```
telegram-history-dump.rb:51:in `exec_tg_command': Telegram command <history> failed: {"error"=>"RPC_CALL_FAIL 400: OFFSET_INVALID", "result"=>"FAIL", "error_code"=>71} (RuntimeError)
	from telegram-history-dump.rb:92:in `block (2 levels) in dump_dialog'
	from /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from telegram-history-dump.rb:91:in `block in dump_dialog'
	from telegram-history-dump.rb:78:in `loop'
	from telegram-history-dump.rb:78:in `dump_dialog'
	from telegram-history-dump.rb:367:in `block in <main>'
	from telegram-history-dump.rb:363:in `each'
	from telegram-history-dump.rb:363:in `each_with_index'
	from telegram-history-dump.rb:363:in `<main>'
```

**Comment by bydioeds** [comment]
https://github.com/vysheng/tg/issues/947
