### ISSUE TITLE
Crash during DL: Failed to download media file, no implicit conversion of nil into String

### ISSUE THREAD

**Issue by BitBargain** [tvdstaaij/telegram-history-dump#87]
```
I, [2017-09-04T17:05:54.818277 #26440]  INFO -- : Dumping "Telegram_Bot_Playground" (range 401-500)
I, [2017-09-04T17:05:55.818537 #26440]  INFO -- : Dumping "Telegram_Bot_Playground" (range 501-600)
I, [2017-09-04T17:05:56.818735 #26440]  INFO -- : Dumping "Telegram_Bot_Playground" (range 601-700)
I, [2017-09-04T17:05:57.818990 #26440]  INFO -- : Dumping "Telegram_Bot_Playground" (range 701-800)
W, [2017-09-04T17:05:58.302767 #26440]  WARN -- : Failed to download media file: no implicit conversion of nil into String
E, [2017-09-04T17:05:58.302861 #26440] ERROR -- : Wrong response on media download for message id 020000003ef9e3005cbf0200000000000000000000000000
W, [2017-09-04T17:05:58.303457 #26440]  WARN -- : Failed to download media file: Broken pipe
E, [2017-09-04T17:05:58.303499 #26440] ERROR -- : Wrong response on media download for message id 020000003ef9e3005abf0200000000000000000000000000
W, [2017-09-04T17:05:58.303852 #26440]  WARN -- : Failed to download media file: Broken pipe
E, [2017-09-04T17:05:58.303904 #26440] ERROR -- : Wrong response on media download for message id 020000003ef9e30052bf0200000000000000000000000000
I, [2017-09-04T17:05:58.819395 #26440]  INFO -- : Dumping "Telegram_Bot_Playground" (range 801-900)
telegram-history-dump.rb:46:in `write': Broken pipe (Errno::EPIPE)
	from telegram-history-dump.rb:46:in `puts'
	from telegram-history-dump.rb:46:in `exec_tg_command'
	from telegram-history-dump.rb:92:in `block (2 levels) in dump_dialog'
	from /usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from telegram-history-dump.rb:91:in `block in dump_dialog'
	from telegram-history-dump.rb:78:in `loop'
	from telegram-history-dump.rb:78:in `dump_dialog'
	from telegram-history-dump.rb:367:in `block in <main>'
	from telegram-history-dump.rb:363:in `each'
	from telegram-history-dump.rb:363:in `each_with_index'
	from telegram-history-dump.rb:363:in `<main>'

```

In telegram-cli:

```
[17%Down]> SIGNAL received
h./telegram-cli(print_backtrace+0x2f)[0x46ef1f]
./telegram-cli(termination_signal_handler+0x64)[0x46efb4]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f202b0184b0]
./telegram-cli(tgl_do_load_photo+0xd)[0x4a0e8d]
./telegram-cli(interpreter_ex+0x970)[0x478e50]
./telegram-cli[0x46f501]
/usr/lib/x86_64-linux-gnu/libevent-2.0.so.5(+0x1938a)[0x7f202c4d238a]
/usr/lib/x86_64-linux-gnu/libevent-2.0.so.5(event_base_loop+0x819)[0x7f202c4c64c9]
./telegram-cli(net_loop+0xa7)[0x470557]
./telegram-cli(loop+0x183)[0x4718c3]
./telegram-cli(main+0x2e5)[0x46d745]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f202b003830]
./telegram-cli(_start+0x29)[0x46d859]

```

It always hangs at the same point, preventing me from archiving the groups.

It could be a telegram-cli bug, but regardless it would be appreciated if I could add groups/ranges to skip to the config file as a workaround.

**Comment by atsp** [comment]
Have the same problem. @BitBargain , have you found any workaround?

**Comment by mxmlnkn** [comment]
Have the same problem. This seems to happen because telegram-cli crashes at will:

     *** 1526384817.650984 Skipped 2484 int out of 3478 (type messages.Messages) (query type get history)
     *** 1526384817.651020 0x00000000 0x0b446ae3 0x00012237 0x1cb5c415
    > telegram-cli: tgl/queries.c:470: tglq_query_result: Assertion `0' failed.
    SIGNAL received
    h./tg/bin/telegram-cli(print_backtrace+0x20)[0x46ebc0]
    ./tg/bin/telegram-cli(termination_signal_handler+0x64)[0x46ec44]
    /lib/x86_64-linux-gnu/libc.so.6(+0x34f00)[0x7fa687fd8f00]
    /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x10b)[0x7fa687fd8e7b]
    /lib/x86_64-linux-gnu/libc.so.6(abort+0x151)[0x7fa687fda231]
    /lib/x86_64-linux-gnu/libc.so.6(+0x2d9da)[0x7fa687fd19da]
    /lib/x86_64-linux-gnu/libc.so.6(+0x2da52)[0x7fa687fd1a52]
    ./tg/bin/telegram-cli(tglq_query_result+0x44c)[0x49745c]
    ./tg/bin/telegram-cli[0x49007f]
    ./tg/bin/telegram-cli[0x4b401b]
    /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5(event_base_loop+0x6a0)[0x7fa689ea55a0]
    ./tg/bin/telegram-cli(net_loop+0xa7)[0x470107]
    ./tg/bin/telegram-cli(loop+0x183)[0x471363]
    ./tg/bin/telegram-cli(main+0x2d6)[0x46d496]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7fa687fc5a87]
    ./tg/bin/telegram-cli(_start+0x2a)[0x46d59a]

Then telegram-history-dump receives nothing at tries to json parse an empty string, crashing telegram-history-dump next.

**Comment by mxmlnkn** [comment]
In telegram-cli it looks a bit different for me:

     *** 1526384817.650984 Skipped 2484 int out of 3478 (type messages.Messages) (query type get history)
     *** 1526384817.651020 0x00000000 0x0b446ae3 0x00012237 0x1cb5c415
    > telegram-cli: tgl/queries.c:470: tglq_query_result: Assertion `0' failed.
    SIGNAL received
    h./tg/bin/telegram-cli(print_backtrace+0x20)[0x46ebc0]
    ./tg/bin/telegram-cli(termination_signal_handler+0x64)[0x46ec44]
    /lib/x86_64-linux-gnu/libc.so.6(+0x34f00)[0x7fa687fd8f00]
    /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x10b)[0x7fa687fd8e7b]
    /lib/x86_64-linux-gnu/libc.so.6(abort+0x151)[0x7fa687fda231]
    /lib/x86_64-linux-gnu/libc.so.6(+0x2d9da)[0x7fa687fd19da]
    /lib/x86_64-linux-gnu/libc.so.6(+0x2da52)[0x7fa687fd1a52]
    ./tg/bin/telegram-cli(tglq_query_result+0x44c)[0x49745c]
    ./tg/bin/telegram-cli[0x49007f]
    ./tg/bin/telegram-cli[0x4b401b]
    /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5(event_base_loop+0x6a0)[0x7fa689ea55a0]
    ./tg/bin/telegram-cli(net_loop+0xa7)[0x470107]
    ./tg/bin/telegram-cli(loop+0x183)[0x471363]
    ./tg/bin/telegram-cli(main+0x2d6)[0x46d496]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7fa687fc5a87]
    ./tg/bin/telegram-cli(_start+0x2a)[0x46d59a]
