### ISSUE TITLE
can not find command 'channel_list'

### ISSUE THREAD

**Issue by narbehaj** [tvdstaaij/telegram-history-dump#97]
Hey there,

I cloned the latest changes from the repo and tried to run it but I got the error below:

`I, [2017-12-22T12:42:45.815431 #10437]  INFO -- : Attaching to telegram-cli control socket at localhost:9009
telegram-history-dump.rb:51:in `exec_tg_command': Telegram command <channel_list> failed: {"result"=>"FAIL", "error_code"=>38, "error"=>"can not find command 'channel_list'"} (RuntimeError)
	from telegram-history-dump.rb:335:in `<main>'`

I have been using exactly this method for past couple of months but this time it didn't work. 
Any idea?

**Comment by vincentkwok** [comment]
`channel_list` it was removed in v1.3.1 https://github.com/vysheng/tg/blob/1.3.1/interface.c#L1292

**Comment by narbehaj** [comment]
@vincentkwok ok thanks, what should I do now to export my conversations?

**Comment by vincentkwok** [comment]
the config is in master branch. Use master branch instead.

**Comment by narbehaj** [comment]
@vincentkwok The telegram-cli is already in the master branch. What do you mean? What config?

**Comment by vincentkwok** [comment]
do you clone & build telegram-cli from master branch? or it was in v.1.3.1 ?

**Comment by narbehaj** [comment]
@vincentkwok yes I did.

**Comment by vincentkwok** [comment]
telegram-history-dump tries to call `channel_list` command. It does NOT in telegram-cli v1.3.1 BUT in master branch. You have to build the telegram-cli binary yourself based on master branch steps below:

1. clone https://github.com/vysheng/tg:master
1. follow [installation](https://github.com/vysheng/tg#installation) to build
1. use built bin/telegram-cli to connect telegram
1. ruby telegram-history-dump.rb

**Comment by narbehaj** [comment]
I did that, but same error :(

**Comment by vincentkwok** [comment]
Can't reproduce :(

**Comment by ChrisDeChef** [comment]
I had the same problem :/ My solution was as simple as reading the command i copied and pasted **c a r e f u l l y**

I had the command compied from my wiki which replaced the two dashes from the command line parameter **--json** into one long dash like **–json**.

So if your telegramcli output looks colorful (it should be plain json) you probably did the same mistake.

**Comment by narbehaj** [comment]
@ChrisDeChef thanks for the note but my problem is not related to --json option. It relates to telegram-cli's new version which does not support channel_list command.
